name: bell
description: A Flutter app that reads Gmail, detects times, and schedules alarms.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: 6.0.2
  googleapis: ^13.1.0
  googleapis_auth: any
  http: any
  flutter_local_notifications: ^17.1.0
  timezone: any
  intl: any
  url_launcher: any
  provider: any
  open_file: ^3.3.2
  path_provider: ^2.1.1
  workmanager: ^0.5.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  android_alarm_manager_plus: ^4.0.3
  android_intent_plus: ^5.1.0
  flutter_linkify: ^6.0.0
  excel: ^4.0.3
  sqflite: ^2.3.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/bell_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/bell_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/client_secret.json

